name: Manually triggered workflow
on:
  workflow_dispatch:

env:
  basename: "showdate"
  agrtable_version: "2-13"

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
#        - {
#            name: "Windows MinGW-w64 (32-bit)",
#            archname: "win32",
#            os: windows-latest,
#            cc: "i686-w64-mingw32-gcc.exe",
#            cxx: "i686-w64-mingw32-g++.exe",
#          }
        - {
            name: "Windows MinGW-w64 (64-bit)",
            archname: "win64",
            os: windows-latest,
            cc: "x86_64-w64-mingw32-gcc.exe",
            cxx: "x86_64-w64-mingw32-g++.exe",
          }
    steps:
    - uses: actions/checkout@v1
    - if: contains( matrix.config.archname, 'win' )
      name: argtable2
      run: |
        curl -k -L -o argtable${{ env.agrtable_version }}.tar.gz -# http://prdownloads.sourceforge.net/argtable/argtable${{ env.agrtable_version }}.tar.gz
        tar xfz argtable${{ env.agrtable_version }}.tar.gz
        cmake -Wno-dev -G"MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=../deps -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL=OFF -Sargtable${{ env.agrtable_version }} -Bbuild_argtable
        make -Cbuild_argtable install/strip
        mkdir deps/include
        copy argtable${{ env.agrtable_version }}/src/argtable2.h deps/include
    - name: Build
      run: |
        dir deps/lib
        make install CC=${{ matrix.config.cc }} CFLAGS="-Ideps/include" LIBS="-Ldeps/lib -largtable2" PREFIX=build_result
    - name: Package
      run: |
        tar cfj ./${{ env.basename }}${{ matrix.config.archname }}.tar.bz2 --strip-components=1 build_result
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: ./${{ env.basename }}${{ matrix.config.archname }}.tar.bz2
        name: ${{ env.basename }}${{ matrix.config.archname }}.tar.bz2
